name: quote_generator
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^6.0.7
  flutter_riverpod: ^2.2.0
  http: ^0.13.5
  flutter_screenutil: ^5.6.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  hive_flutter: ^1.1.0
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  fonts:
<<<<<<< HEAD
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-Bold.ttf
        - asset: assets/fonts/Dosis-ExtraBold.ttf
        - asset: assets/fonts/Dosis-Light.ttf
        - asset: assets/fonts/Dosis-ExtraLight.ttf
        - asset: assets/fonts/Dosis-Medium.ttf
        - asset: assets/fonts/Dosis-Regular.ttf
        - asset: assets/fonts/Dosis-SemiBold.ttf
      

=======
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 300
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 300
>>>>>>> main
